routes/web.php
<?php

use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ShoppingController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::resource('products', ProductController::class, ['name' => 'products'])->middleware(['auth', 'verified', 'role:user']);
Route::resource('shoppings', ShoppingController::class, ['name' => 'shoppings'])->middleware(['auth', 'verified', 'role:admin,user']);
Route::resource('invoices', InvoiceController::class, ['name' => 'invoices'])->middleware(['auth', 'verified', 'role:admin,user']);
Route::post('shoppings/all', [InvoiceController::class, 'storeAll'])->name('shopping.all')->middleware(['auth', 'verified', 'role:admin']);

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Shopping.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Shopping extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'name',
        'status',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function products()
    {
        return $this->belongsToMany(Product::class);
    }

    public function invoice()
    {
        return $this->hasOne(Invoice::class);
    }
}

app/Http/Controllers/ShoppingController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Product;
use App\Models\Shopping;
use Illuminate\Http\Request;

class ShoppingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Shopping $shopping)
    {
        $this->authorize('view', $shopping);
        $shoppings = Shopping::where('status', 'open')->get();
        return view('shoppings.index', ['shoppings' => $shoppings]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::findOrFail(auth()->user()->id);
        $date = date("h:i:sa");
        $product = $request->id;
        $shopping = Shopping::where('user_id', $user->id)->where('status', 'open')->get();
        if ($shopping->isEmpty()) {
            $newShopping = new Shopping([
                'name' => "$user->name $date",
                'status' => 'open',
            ]);
            
            $user->shoppings()->save($newShopping);
            
            $newShopping->products()->syncWithoutDetaching([$product]);
            
            $newShopping->save();
        }
        
        if ($shopping->isNotEmpty()) {
            $shopping->last()->products()->syncWithoutDetaching([$product]);
        }

        return redirect()->route('products.index')->with('success', 'Agregado');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Shopping  $shopping
     * @return \Illuminate\Http\Response
     */
    public function show(Shopping $shopping)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Shopping  $shopping
     * @return \Illuminate\Http\Response
     */
    public function edit(Shopping $shopping)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Shopping  $shopping
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Shopping $shopping)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Shopping  $shopping
     * @return \Illuminate\Http\Response
     */
    public function destroy(Shopping $shopping)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/shoppings/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Products') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    @include('partials.alert')
                    
<div class="overflow-x-auto relative">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="py-3 px-6">
                    name
                </th>
                <th scope="col" class="py-3 px-6">
                    status
                </th>
                <th scope="col" class="py-3 px-6">
                    user
                </th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            
            @forelse ($shoppings as $shopping)
                <tr class="bg-white dark:bg-gray-800">
                    <th scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                       {{$shopping->name}}
                    </th>
                    <td class="py-4 px-6">
                        {{$shopping->status}}
                    </td>
                    <td class="py-4 px-6">
                        {{$shopping->user->name}}
                    </td>
                    <td>
                        <form method="post" action="{{ route('invoices.store') }}"> 
                            @csrf
                            @method('POST')
                            <input type="hidden" name="id" value="{{$shopping->id}}">
                            <button type="submit">Generar factura</button>
                        </form>
                    </td>
                </tr>
                    
                @empty
                <tr>
                    <td>No hay productos</td>    
                </tr> 
                @endforelse
        </tbody>
    </table>
</div>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>